[package]
name = "cmark_xml"
version = "0.1.0"
edition = "2021"
authors = ["Hanabusa Masahiro <>"]
publish = false
license = "MIT"
workspace = ".."

[lib]
name = "cmark_xml"
path = "src/lib.rs"

[dependencies]
comrak = "0.14"
minidom = "0.15"
log = "0.4"
toml = "0.5"

